name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  schedule:
      - cron:  '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up sqlite-utils
      run: pip install sqlite-utils

    - name: Run
      run: |
        since=$(sqlite3 github-statistics.db 'SELECT id FROM users ORDER BY id DESC LIMIT 1')
        curl \
          -H "Accept: application/vnd.github.v3+json" \
          -S \
          -s \
          "https://api.github.com/users?per_page=100&since=${since}" | \
        sqlite-utils insert github-statistics.db users - --pk=id

    - name: Commit changes
      run: |
        git config --global user.email "$(id -un)@$(uname -n)"
        git config --global user.name "$(id -un)"
        git add github-statistics.db
        if git commit -m 'Update github-statistics.db'
        then
          git push
        fi
