name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up sqlite-utils
      run: pip install sqlite-utils

    - name: Run
      run: |
        curl \
          -H "Accept: application/vnd.github.v3+json" \
          -i \
          https://api.github.com/users?per_page=100

    - name: Commit changes
      run: |
        git config --global user.email "$(id -un)@$(uname -n)"
        git config --global user.name "$(id -un)"
        git add github-statistics.db
        git commit -m 'Update github-statistics.db'
        git push
