name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up SQLite
      run: |
        apt-get update
        apt-get -y install sqlite3

    - name: Run
      run: |
        curl \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/users
