name: Users

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  workflow_dispatch:
  # schedule:
  #     - cron:  '30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up sqlite-utils
      run: pip install sqlite-utils

    - name: Decompress database
      run: /usr/bin/tar --use-compress-program zstd -xf github-users.tzst

    - name: Run
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        remaining=1
        query='SELECT id FROM users ORDER BY id DESC LIMIT 1'
        while [ -n "$remaining" ] && [ $remaining -gt 0 ]
        do
          since=$(sqlite3 github-users.db "$query")
          if curl \
            -D store.txt \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -S \
            -s \
            "https://api.github.com/users?per_page=100&since=${since}" \
            > users.json
            grep -q 'HTTP/2 200' store.txt
          then
            sqlite-utils insert github-users.db users - --pk=id \
            < users.json
          else
            reset=$(grep 'x-ratelimit-reset' store.txt)
            echo "$reset"
            reset=$(echo "$reset" | tr -cd '[:digit:]')

            remaining=$((reset - $(date +%s)))
            if [ $remaining -gt 0 ]
            then
                echo "$remaining seconds until rate limit reset"
            fi

            grep -Eo '("message":)\s*(".*")' users.json | tr -d '"'
            exit
          fi

          remaining=$(grep 'x-ratelimit-remaining' store.txt)
          echo "$remaining"
          remaining=$(echo "$remaining" | tr -cd '[:digit:]')
        done

    - name: Compress database
      run: |
        rm github-users.tzst
        /usr/bin/tar \
          --use-compress-program zstd \
          -cf github-users.tzst github-users.db

    - name: Commit changes
      run: |
        git config --global user.email "$(id -un)@$(uname -n)"
        git config --global user.name "$(id -un)"
        git pull
        git add github-users.tzst
        if git commit -m 'Update github-users.tzst'
        then
          git push
        fi
